#!/bin/bash

iters=`seq 1 500`

date '+%A %W %Y %X'

echo "start"
date
(for i in $iters 
do
./randread /usr  123$i 0.5  0.7 ; 
done
echo "1 done"
date ) &

(for i in $iters 
do
./randread /home 125$i 0.8  0.8
done
echo "2 done"
date ) &

(for i in $iters 
do
./randread /etc 778$i 0.9  0.8
done
echo "3 done"
date ) &

(for i in $iters 
do
./randread /bin     523$i 0.3  0.6 
done
echo "4 done"
date ) &

(for i in $iters 
do
./randread /usr 135$i 0.9  0.8 
done
echo "5 done"
date ) &

(for i in $iters 
do
./randread /home 623$i 0.9  0.8 
done
echo "6 done"
date ) &

(for i in $iters 
do
./randread /etc  923$i 0.5  0.7 
done
echo "7 done"
date ) &

(for i in $iters 
do
./randread /   823$i 0.3  0.6 
done
echo "8 done"
date ) &

(for i in $iters 
do
./randread /usr  123$i 0.5  0.7 ; 
done
echo "1 done"
date ) &

(for i in $iters 
do
./randread /home 125$i 0.8  0.8
done
echo "2 done"
date ) &

(for i in $iters 
do
./randread /etc 778$i 0.9  0.8
done
echo "3 done"
date ) &

(for i in $iters 
do
./randread /bin     523$i 0.3  0.6 
done
echo "4 done"
date ) &

(for i in $iters 
do
./randread /usr 135$i 0.9  0.8 
done
echo "5 done"
date ) &

(for i in $iters 
do
./randread /home 623$i 0.9  0.8 
done
echo "6 done"
date ) &

(for i in $iters 
do
./randread /etc  923$i 0.5  0.7 
done
echo "7 done"
date ) &

(for i in $iters 
do
./randread /   823$i 0.3  0.6 
done
echo "8 done"
date ) &


wait
date '+%A %W %Y %X'
